### PR TITLE
Fixed: Several IllegalArgumentExceptions

### PR DESCRIPTION
**Pull request by dtrunk90**
Don't use all service parameters in where condition since entities don't have all fields which results in:

java.lang.IllegalArgumentException: FieldName product not found for entity: ProductStore
	at org.apache.ofbiz.entity.condition.EntityExpr.checkRhsType(EntityExpr.java:199)
	at org.apache.ofbiz.entity.condition.EntityExpr.makeWhereString(EntityExpr.java:118)
	at org.apache.ofbiz.entity.condition.EntityJoinOperator.addSqlValue(EntityJoinOperator.java:74)
	at org.apache.ofbiz.entity.condition.EntityConditionListBase.makeWhereString(EntityConditionListBase.java:77)
	at org.apache.ofbiz.entity.condition.EntityJoinOperator.addSqlValue(EntityJoinOperator.java:74)
	at org.apache.ofbiz.entity.condition.EntityConditionListBase.makeWhereString(EntityConditionListBase.java:77)
	at org.apache.ofbiz.entity.datasource.GenericDAO.makeConditionWhereString(GenericDAO.java:828)
	at org.apache.ofbiz.entity.datasource.GenericDAO.selectListIteratorByCondition(GenericDAO.java:732)
	at org.apache.ofbiz.entity.datasource.GenericHelperDAO.findListIteratorByCondition(GenericHelperDAO.java:140)
	at org.apache.ofbiz.entity.GenericDelegator.find(GenericDelegator.java:1579)
	at org.apache.ofbiz.entity.GenericDelegator.findList(GenericDelegator.java:1613)
	at org.apache.ofbiz.entity.util.EntityQuery.query(EntityQuery.java:455)
	at org.apache.ofbiz.entity.util.EntityQuery.queryList(EntityQuery.java:380)
	at org.apache.ofbiz.entity.util.EntityQuery.queryOne(EntityQuery.java:421)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at ProductStoreServices.isStoreInventoryAvailableOrNotRequired(ProductStoreServices.groovy:357)

### CODE REVIEW

**Comment by nmalin** [comment]
Hello danny thanks for your issue, just before I wish control why the EntityQuery doesn't resolve correctly the pk on context

**Comment by dtrunk90** [comment]
FYI: I'm running an older ofbiz version here, not trunk. I just noticed this happened here after cherry picking the whole history of `ProductStoreServices.groovy`. Sorry, should have mentioned that before. I don't know if this issue still persists on trunk, but it was here. Maybe I'm just missing a commit which resolves the PK only from the service context.

**Comment by dtrunk90** [comment]
Yeah, sorry. This was an issue on my side only. After picking 3080813151974e237b80e45ebcb6a1db5b775d43 and 7d3ad82758820c5a83dbe821d52bb46918aaa134 it works.

**Comment by nmalin** [comment]
No worries @dtrunk90 happy that you solved you pb. If you found a potential one, don't hesitate to submit it

**Pull request closed without merging**
