### PR TITLE
Implemented: Shipment Note functionalities

### PR DESCRIPTION
**Pull request by PierreSmits**
(OFBIZ-11236)(OFBIZ-11344)(OFBIZ-11345)

Added: entity-model, labels, services, widgets for Shipment Notes
Added: related shipment menus and items
updated: list forms with grid definitions
removed: ShipmentTabBar.ftl
removed: menu items in containers in screens

Thanks go out to:
Pierre Gaudin (Nereide) for co-authoring the larger portion of the shipment note functionalities
Jacques Leroux for input and review
Devanshu Vias for input and review

### CODE REVIEW

**Comment by JacquesLeRoux** [comment]
Hi Pierre, this in your commit comment does not make sense to me.

> (OFBIZ-1134)(OFBIZ-11345)

both (actually 11134) are commited and closed 

Also I'm still waiting for Pierre Gaudin to check the issue I got. Anyway I'll appy locally and test...

**Comment by PierreSmits** [comment]
What can you say: typos happen.

It is actually OFBIZ-11344

Thanks for the review Jacques.

**Comment by JacquesLeRoux** [comment]
Actually the real question was: should we keep these references in the commit comment?

**Comment by mbrohl** [comment]
The committer should take care of the commit quality and either decline the PR when the quality is not sufficient or do changes by squashing or manually merging the commits (no fast forwards).

A commit with several Jira references should either be split into single commits with one reference or as one commit with reference to the parent issue, IMO.

**Comment by JacquesLeRoux** [comment]
Actually, after the wrong reference to a Jira, the confusion came from me. I added a 1 as a header when it was more a 4 as a trailer missing. Then I added a 5 at the end to get to the other one, and of course those Jiras are unrelated, sorry for that. So I remove my question, there are no issue in comment.
Anyway, 
1. I'll call Pierre Gaudin again,
2. w/o answer I'll review the ticket again
3. if needed I'll work on it if nobody else wants

**Comment by PierreSmits** [comment]
@JacquesLeRoux

It seems to me that sufficient time has passed.

**Comment by PierreSmits** [comment]
Can't be merged anymore.

**Pull request closed without merging**
