### PR TITLE
Remove old unused fields from entity [OFBIZ-12858]

### PR DESCRIPTION
**Pull request by pushprajsinghjadoun**
Removed unused old fields (deprecated) exist.

- oldPickStartDate
- oldMaritalStatus
- oldSquareFootage
- oldInvoiceSequenceEnumId
- oldOrderSequenceEnumId
- oldQuoteSequenceEnumId

### CODE REVIEW

**Comment by JacquesLeRoux** [comment]
Hi @pushprajsinghjadoun,

If we remove oldMaritalStatus, we can also remove UpgradeServices.java in party and its reference in services_upgrade.xml (in party)

Did you intentionnaly keep oldInvoiceSequenceEnumId in InvoiceServicesScript.groovy?
Same question for oldOrderSequenceEnumId and oldQuoteSequenceEnumId in OrderServicesScript.groovy.

Are you aware of https://cwiki.apache.org/confluence/display/OFBIZ/Revisions+Requiring+Data+Migration+-+upgrade+ofbiz ?

TIA

**Comment by pushprajsinghjadoun** [comment]
Hi @JacquesLeRoux ,

Thanks for sharing the suggestion, I will review it again and remove the unused field references.

**Comment by pushprajsinghjadoun** [comment]
Hi @JacquesLeRoux,

I have made the changes as per your suggestion. Can you please review them again?

**Comment by JacquesLeRoux** [comment]
Hi @pushprajsinghjadoun ,

Sounds good to me, just that you missed to remove oldQuoteSequenceEnumId in OrderServicesScript.groovy.

Also please think about what to do, if necessary, in https://cwiki.apache.org/confluence/display/OFBIZ/Revisions+Requiring+Data+Migration+-+upgrade+ofbiz. I did not, too lazy (too hot here) :)

**Comment by pushprajsinghjadoun** [comment]
Hi @JacquesLeRoux ,

I apologize for not removing the oldQuoteSequenceEnumId field from the QuoteServicesScript.groovy file. I have now removed it.

Also, I am having trouble understanding what you are referring to in this document: https://cwiki.apache.org/confluence/display/OFBIZ/Revisions+Requiring+Data+Migration+-+upgrade+ofbiz.

**Comment by JacquesLeRoux** [comment]
Hi @pushprajsinghjadoun,

Don't worry about the wiki page. I checked there is nothing to do there, all was already documented there or very old (>10 years). Thanks for your work, I'll push it now.

**Pull request merged**
