### PR TITLE
OFBIZ-12989

### PR DESCRIPTION
**Pull request by gtchaboussie**
Improved:
Implemented:
Documented:
Completed:
Reverted:
Fixed:
(OFBIZ-)

Explanation

Thanks:

### CODE REVIEW

**Comment by mbrohl** [comment]
Hi @gtchaboussie ,

some hints: please stick to our commit message template for proper commit messages.
Also, please create a PR with the OFBiz Jira issue numer in the title (OFBIZ-XXXXX). This will allow Jira to automatically link the PR to the Jira issue.

Thanks!

**Comment by gtchaboussie** [comment]
Hi @mbrohl thanks for the advices. I thought i'd squash the commits and edit the commit message at that time, is that ok ?
I'll edit the PR name right away.

**Comment by JacquesLeRoux** [comment]
Hi @gtchaboussie ,

Yes that works too

**Comment by JacquesLeRoux** [comment]
Hi @gtchaboussie,

I'm working on https://issues.apache.org/jira/browse/OFBIZ-12985, for now https://issues.apache.org/jira/browse/OFBIZ-12995 as a 1st step, so there are few conflicts in accoutning and there will be more in all applications. I suggest that you wait or often update your branch because these fixes have priority. We can't get ahead (freezing a 24.xx branch notably) w/o the integration tests all working. TIA

**Comment by gtchaboussie** [comment]
thanks for the heads up. I'll focus on https://issues.apache.org/jira/browse/OFBIZ-12991 for now.

**Comment by JacquesLeRoux** [comment]
Hi @gtchaboussie,

So you can squash? I thought we could only squash when merging. At least as a committer I see no squash option alone, only "Squash and merge"

**Pull request closed without merging**
