### PR TITLE
Improved: allow uploading ZUGFeRD compliant pdf files (OFBIZ-12920)

### PR DESCRIPTION
**Pull request by originalnichtskoenner**
Improved: Allow uploading non-empty pdf files.

Use ZUGFeRD parser to validate those files. Can be configured in security.properties.
See https://github.com/ZUGFeRD/mustangproject for more information.

### CODE REVIEW

**Comment by danwatford** [comment]
Hi @originalnichtskoenner ,

Please could you raise a corresponding jira issue at https://issues.apache.org/jira to describe what problem is being solved or what feature is being added to OFBiz by this PR.

If the problem being solved is complex, it may be worth starting a discussion on the OFBiz mailing lists: https://ofbiz.apache.org/mailing-lists.html

**Comment by originalnichtskoenner** [comment]
Hi @danwatford ,
i created an issue. Thanks for your reply! https://issues.apache.org/jira/browse/OFBIZ-12920

**Comment by PierreSmits** [comment]
Hi  Johannes, @originalnichtskoenner 

If you add the ticket Id of the JIRA ticket in the subject of a Pull Request, the Pull Request will always be referenced in JIRA.

**Comment by originalnichtskoenner** [comment]
FYI: It seems like a broke something (testFopMacroLibrary keeps failing) with my change. Would like to leave the PR as draft until i figure it out.

**Comment by originalnichtskoenner** [comment]
> Hi Johannes, @originalnichtskoenner
> 
> If you add the ticket Id of the JIRA ticket in the subject of a Pull Request, the Pull Request will always be referenced in JIRA.

Just saw it show up in jira. Very nice 👍

**Comment by JacquesLeRoux** [comment]
> FYI: It seems like a broke something (testFopMacroLibrary keeps failing) with my change. Would like to leave the PR as draft until i figure it out.

Sure thing

**Comment by originalnichtskoenner** [comment]
Alright I think I am happy with the changes now. I had to downgrade the dependency version (2.10.0 -> 2.8.0) to avoid breaking tests.

For testing purposes I created a [sample_invoice.pdf](https://github.com/apache/ofbiz-framework/files/14434415/sample_invoice.pdf) (using this Plugin for Libreoffice https://github.com/akretion/factur-x-libreoffice-extension) and uploaded it as PartyContent via EditPartyContents in the Party Manager.

**Comment by PierreSmits** [comment]
Hi Johannes,

Please upload your files in the ticket, otherwise they get lost after tonight's redeployment of demo-trunk. It would otherwise hard to evaluate the impact and/or benefit of this improvement.

Best regards,
Pierre

**Comment by originalnichtskoenner** [comment]
> Hi Johannes,
> 
> Please upload your files in the ticket, otherwise they get lost after tonight's redeployment of demo-trunk. It would otherwise hard to evaluate the impact and/or benefit of this improvement.
> 
> Best regards, Pierre

Hi Pierre,
I just uploaded them to my local OFBiz instance for testing. I added them to the PR so you can test it for yourselves if you want.
I can attach them to the ticket in Jira as well i you prefer that.

**Comment by originalnichtskoenner** [comment]
> I can attach them to the ticket in Jira as well i you prefer that.

Done.

**Pull request merged**
