### PR TITLE
Improved: Seo translation for Content, Product and Category alternatives urls (OFBIZ-12329)

### PR DESCRIPTION
**Pull request by CharlesNereide**
Improved: Seo translation for Content, Product and Category
Fixed: get alt url before retrieving the name or description from record
Fixed: the mandatory character '/' for objectInfo alternative url

### CODE REVIEW

**Comment by JacquesLeRoux** [comment]
Seems that it's too late

```
C:\projectsASF\Git\ofbiz-framework>git checkout -b CharlesNereide-seo-improvements trunk
Switched to a new branch 'CharlesNereide-seo-improvements'

C:\projectsASF\Git\ofbiz-framework>git pull https://github.com/CharlesNereide/ofbiz-framework.git seo-improvements
From https://github.com/CharlesNereide/ofbiz-framework
 * branch                  seo-improvements -> FETCH_HEAD
Auto-merging applications/product/src/main/java/org/apache/ofbiz/product/category/ftl/CatalogUrlSeoTransform.java
CONFLICT (content): Merge conflict in applications/product/src/main/java/org/apache/ofbiz/product/category/ftl/CatalogUrlSeoTransform.java
error: could not apply 83c2637d2e... Improved: Use replace() instead of replaceAll() when a regex is not used (OFBIZ-10934)
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Recorded preimage for 'applications/product/src/main/java/org/apache/ofbiz/product/category/ftl/CatalogUrlSeoTransform.java'
Could not apply 83c2637d2e... Improved: Use replace() instead of replaceAll() when a regex is not used (OFBIZ-10934)
```

**Comment by PierreSmits** [comment]
What a pity. The contributor spent precious time to get this improvement to the project. And it got wasted.

**Comment by JacquesLeRoux** [comment]
I totally agree. I tried to follow GH advice but it's really too late. It's a mess impossible to fix but if we are able to merge CatalogUrlSeoTransform.java, not an easy task to be sure of the result :/

**Comment by JacquesLeRoux** [comment]
Note that it can still be reopened...

**Pull request closed without merging**
