### PR TITLE
Improved: Address SpotBugs issue by avoiding nulls in parameter matches for JMockit Expectations (OFBIZ-11456)

### PR DESCRIPTION
**Pull request by danwatford**

### CODE REVIEW

**Comment by danwatford** [comment]
Ignoring the failed checks from jquery javascript files as unrelated to this PR.

**Comment by JacquesLeRoux** [comment]
Thanks @danwatford, 

Sounds good to me, I have updated the same at line 847. Do you want to keep the unused genericSubHyperlinkRenderedExpectation method there?

**Comment by danwatford** [comment]
Hi Jacques, 
I would rather not remove anything until I get back to the refactoring work for MacroFormRenderer. There was a lot of code that I was gradually separating into different modules/classes, but it meant there was/is some duplication of code during intermediate steps.

**Comment by JacquesLeRoux** [comment]
OK Daniel,

It's up to you :)

**Pull request merged**
