### PR TITLE
Implemented: Add 'controlPath' attribute

### PR DESCRIPTION
**Pull request by PierreSmits**
(OFBIZ-11317)

added: Missed aspected in header.ftl in bluelight theme

### CODE REVIEW

**Comment by JacquesLeRoux** [comment]
Commited, thanks Pierre

**Comment by PierreSmits** [comment]
What did you do?
After this I get in my local clone:

> git --no-optional-locks -c color.branch=false -c color.diff=false -c color.status=false -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree fetch --prune OFBiz 
>fatal: Cannot fetch both refs/pull/13/head and refs/heads/pr/13 to refs/remotes/OFBiz/pr/13
>Completed with errors, see above

**Comment by JacquesLeRoux** [comment]
As answered on dev ML
> I just made a commit and a push after cherry-picking your commit from PR13

**Comment by JacquesLeRoux** [comment]
Maybe I should not have pushed to all branches but only trunk. I'll try that next time
I have checked this feature to push together R17 and R18 when backporting
13 h 55
So we need to delete the ‘refs/pull/13/head’ from remote, right?
Pierre Smits  [13 h 47]
That appears to be the way to go.
Jacques Le Roux  [13 h 50]
Done, how it goes on your side?
Both local and remote deleted
Pierre Smits  [13 h 51]
Let me check.
It seems ok now (and again). I see all available (and implemented PR) branches. As it should be.
13 h 56
OK, I guess it was the push ALL which created the issue (modifié)

**Pull request closed without merging**
