### PR TITLE
Improved: VIEW permissions - invoice contact mechs (OFBIZ-12428)

### PR DESCRIPTION
**Pull request by PierreSmits**
Though there is an entity InvoiceContactMech, this cannot be accessed by user with VIEW permissions when accessing an invoice.
See:
for entity data: https://demo-trunk.ofbiz.apache.org/webtools/control/entity/find/InvoiceContactMech
test invoice: https://demo-trunk.ofbiz.apache.org/accounting/control/invoiceOverview?invoiceId=demo11001

Modified:
AccountingMenus.xml
- added menu-item for contact mechs to InvoiceTabBar menu
controller.xml
- added request-map and view-map for request invoiceContactMech
InvoiceScreens.xml
- added screen for invoice contact mech(s)
InvoiceForms.xml
- added grid to display contact mech details

### CODE REVIEW

**Comment by JacquesLeRoux** [comment]
Hi Pierre,

Did you check locally? It seems we have a test issue.

**Comment by PierreSmits** [comment]
HI Jacques,

Yes I did. Are you referring to the 'Java CI with Gradle/build (pull_request) failing check mentioned above?

It seems there is something weird going on there.
I did the obligatory **./gradlew cleanAll loadAll testIntegration**. Beyond the multitude of errors we see all the time with running the integration test, I could not find anything wrong (may have overlooked something). 
Subsequently I did the **./gradlew ofbiz** in my dev setup, and activated the invoiceContactMech request for invoice="demo11001", no records shown. After adding an InvoiceContactMech record via entity management in webtools for the same invoice, I refreshed the aforementioned screen and data appears. So everything seems ok.

**Comment by PierreSmits** [comment]
Hi @JacquesLeRoux,

You have anymore insights?

**Comment by PierreSmits** [comment]
Hi Jacques,

It appears everything is ok now. Was the missing label the culprit?

**Pull request merged**
