### PR TITLE
Improvement: label OrderAdjustmentType (OFBIZ-12234)

### PR DESCRIPTION
**Pull request by PierreSmits**
Improved: OrderAdjustmentType.Description label for VAT
(OFBIZ-12234)
Added the labels for DE, EN and NL

### CODE REVIEW

**Comment by JacquesLeRoux** [comment]
Hi Pierre,

Would you mind adding 

`<value xml:lang="fr">TVA</value>`

in your forked repo and then update this PR? TIA :)

**Comment by PierreSmits** [comment]
Jaqcues,

The pull request is good enough, and can be merged as such. 

When committed it will create an opportunity for other contributors to enhance when that need arises. I would not want to deprive others from participating.

Best regards,
Pierre

**Comment by JacquesLeRoux** [comment]
Oh, too bad, it's impossible to me to add the change in your forked repo. I can merge/push as is but then I need to redo the trivial work again locally and commit from there.

**Comment by PierreSmits** [comment]
Yeah. Let's not bother with trivial work....

**Comment by PierreSmits** [comment]
You don't have to do everything yourself, Jacques. Don't deprive other contributors of the opportunity. :smile:

**Pull request merged**
