### PR TITLE
Improved: Integrate AR Past Due into accounting-main (OFBIZ-12966)

### PR DESCRIPTION
**Pull request by PierreSmits**
Integrate the overview of invoices past due of accounts receivable as a portal page intoo the main screen of the accounting application.

modified:
- AccountingUiLabels.xml: added label AccountingAccountsReceivable
- AccountingPortletData.xml: added PortalPortlet, PortalPage, PortalPageColumn and PortalPagePortlet
- CommonScreens.xml: added (for portal page handling): field setter, script and incude-portal-page in screen Main
- InvoiceForms.xml: added grid ListArReport
- InvoiceScreens.xml: added screen InvoicesArPastDue

### CODE REVIEW

**Comment by JacquesLeRoux** [comment]
We got some conflicts here

**Comment by PierreSmits** [comment]
Indeed it has. Due to https://github.com/apache/ofbiz-framework/commit/c7333c0c93940a8bfeaab78e282a447755be8ab8 which happened at 12.11 today...

**Comment by PierreSmits** [comment]
Merged the main branch into the PR branch. Conflicts resolved.

**Comment by JacquesLeRoux** [comment]
Hi Pierre,

After getting locally to https://localhost:8443/accounting/control/main just got this:
>java.lang.RuntimeException: Could not find PortalPage with portalPageId [] 

Just try before pushing PRs :/

**Comment by PierreSmits** [comment]
Hi Jacques,

Did you load the following from the changes in AccountingPortletData.xml into your local running instance and cleared the cache:
`
    <PortalPortlet portalPortletId="InvoiceArPastDue" portletName="AR Invoices Past Due" screenName="InvoicesArPastDue"
            screenLocation="component://accounting/widget/InvoiceScreens.xml" description="Invoices Past Due in Accounts Receivable"/>
    <PortalPage portalPageId="ACC_MAIN" portalPageName="Accounting Main Page" description="The main portal page of the Accounting application" ownerUserLoginId="_NA_" sequenceNum="1"/>
    <PortalPageColumn columnSeqId="00001" portalPageId="ACC_MAIN"/>
    <PortalPagePortlet columnSeqId="00001" portalPageId="ACC_MAIN" portalPortletId="InvoiceArPastDue" portletSeqId="00001" sequenceNum="1"/>`

Without that the 'Could not find PortalPage with portalPageId [] is shown.

**Comment by JacquesLeRoux** [comment]
Must be that, trying, thanks

**Comment by JacquesLeRoux** [comment]
Works, I feel the main page makes more sense now. I guess you will put AP invoices list below AR?

**Comment by JacquesLeRoux** [comment]
I fastly tried to show something more helping than 
> Could not find PortalPage with portalPageId []

in those cases, it's too long

**Comment by PierreSmits** [comment]
@JacquesLeRoux,

Great! (That it works). 

RE:  I guess you will put AP invoices list below AR?
There are many options available (e.g. AR portal pages besides AP portal pages, and 'due now' above 'due soon'.

However, I feel the community must decide how to move forward with this and the phasing out of the AR and AP applications. See also interactions in OFBIZ-12918

**Comment by JacquesLeRoux** [comment]
Indeed I remember now Leila's comments at OFBIZ-12918. How long this situation is expected to last?

**Comment by PierreSmits** [comment]
Which situation?

And in general: ask nobody. Nobody knows... ;)

**Comment by JacquesLeRoux** [comment]
The situation about Leila's question:
>I was warning you because I notice the broken screen when doing tests for my last Jira. I propose to add it just to repair the screen during the time that Jiras [OFBIZ-10552](https://issues.apache.org/jira/browse/OFBIZ-10552) and [OFBIZ-12966](https://issues.apache.org/jira/browse/OFBIZ-12966) are managed.
Is it ok for you ?

For the rest 
1. Where adding the AR andAP "invoices due screens" in accounting;
2. then removing AR and AP components

we could resurrect, but better create a last thread to get a consensus
What do you think?

**Pull request merged**
