### PR TITLE
Fixed: Induction from DB does not represent relations properly (OFBIZ-12178)

### PR DESCRIPTION
**Pull request by bjugl**
Fixed: Induction from DB does not represent relations properly.
(OFBIZ-12178)

### CODE REVIEW

**Comment by PierreSmits** [comment]
Hi @bjugl,

 I tried to merge the commits in this PR into a test branch (based on current trunk), and it didn't go through. Multiple rejection files were created.

**Comment by PierreSmits** [comment]
HI @bjugl,

Please consider (for next time around) to keep the ticket id on the first line. Otherwise the PR won't be referenced in the ticket.

**Comment by mbrohl** [comment]
> I tried to merge the commits in this PR into a test branch (based on current trunk), and it didn't go through. Multiple rejection files were created.

This PR is targeted towards the 18.12 release branch, it's not for trunk.

**Comment by mbrohl** [comment]
> Please consider (for next time around) to keep the ticket id on the first line. Otherwise the PR won't be referenced in the ticket.

Fixed.

**Comment by bjugl** [comment]
Thank you, Michael.

**Comment by PierreSmits** [comment]
> > I tried to merge the commits in this PR into a test branch (based on current trunk), and it didn't go through. Multiple rejection files were created.
> 
> This PR is targeted towards the 18.12 release branch, it's not for trunk.

Thanks for the update, @mbrohl 
The ticket, however, states otherwise. 
Furthermore, the description (given on Feb 16 of this year) does not indicate that this improvement solely applies to the branch started almost 3 years ago. Of course, it could be the case. But shouldn't that be reflected in the ticket?

**Comment by mbrohl** [comment]
It's clearly stated, please have a look at the information below the title.
Both target an source branches are named with reference to the 18.12 branch: "bjugl wants to merge 1 commit into apache:release18.12 from ecomify:OFBIZ-12178_ModelInduce_Relations_18_12"

There already was a commit to trunk, this is the backport PR.

**Comment by PierreSmits** [comment]
Thanks, Michael.

**Pull request merged**
