### PR TITLE
OFBIZ-11446 Improved: Convert ContentPermissionServices.xml mini lang to groovy

### PR DESCRIPTION
**Pull request by wpaetzold**
Improved:Convert ContentPermissionServices.xml mini lang to groovy
(OFBIZ-11446)

Also change the reference in DataResourcePermissionServices.xml for checkOwnership

### CODE REVIEW

**Comment by JacquesLeRoux** [comment]
Hi Wiebke,

Just a cursory review for now, please respect the max linelenght (150), TIA

**Comment by wpaetzold** [comment]
Hi @JacquesLeRoux,
I did not notice that I exceeded the max line length.
I am sorry about this and I will gladly correct it.
Is there a formatter for eclipse that can check this?
Because my current plugins unfortunately cannot do this.
TIA

**Comment by JacquesLeRoux** [comment]
Hi Wiebke,

Yes: in https://cwiki.apache.org/confluence/display/OFBIZ/Coding+Conventions, HTH

**Comment by PierreSmits** [comment]
Is this still not good enough to merge?

**Comment by nmalin** [comment]
Hello, I merged it from my local after some groovy simplifiaction.

Thanks @wpaetzold

**Pull request closed without merging**
