### PR TITLE
Improved: redundancy removal (OFBIZ-12404)

### PR DESCRIPTION
**Pull request by PierreSmits**
modified: InvoiceScreens.xml
removed redundant property-maps for Party and Product labels from InvoiceOverview

### CODE REVIEW

**Comment by JacquesLeRoux** [comment]
Hi Pierre,

Even if it obvious for you (once done), it would have been great if you had added that these lines duplicated those in main-decorator (I guess)

**Comment by PierreSmits** [comment]
Thanks Jacques, for your constructive comment. Context is addressed in the ticket, which will be seen by existing and potential adopters when the release notes are generated for a new release. Context provided in the commit is not referenced there.

**Comment by JacquesLeRoux** [comment]
Right, but it would not have hurt to have it here too :unamused:

**Comment by PierreSmits** [comment]
Jacques, 
Please consider that this may trigger someone to cry wolf again, as we have seen in recent days. Let it go. For harmony (and happy collaborating) sake.

**Pull request merged**
