### PR TITLE
Swap date Time field in French (OFBIZ-12822)

### PR DESCRIPTION
**Pull request by MaximeFlame**
Swap dateTime field in French

From
image

To
image

/!\ ONLY IN FRENCH UI LANGUAGE

EDIT : 

[OFBIZ-12822](https://issues.apache.org/jira/browse/OFBIZ-12822)

Thanks:
Néréide

### CODE REVIEW

**Comment by danwatford** [comment]
Hi @MaximeFlame , please could you double check which jira issue this PR relates to.

**Comment by MaximeFlame** [comment]
> Hi @MaximeFlame , please could you double check which jira issue this PR relates to.

I didn't saw on jira that 12818 was already used.
I edited to 12822

**Comment by danwatford** [comment]
> > Hi @MaximeFlame , please could you double check which jira issue this PR relates to.
> 
> I didn't saw on jira that 12818 was already used. I edited to 12822

Hi @MaximeFlame - I cannot view ticket OFBIZ-12822.   

Have you created a Jira Issue corresponding to this PR? If so, please provide a link to the issue. 

I would like to better understand the issue this PR is addressing as it may apply to languages other than French. Those sorts of discussion would be done in the comments of the Jira, and/or the mailing list if particularly complex.

**Comment by MaximeFlame** [comment]
> > > Hi @MaximeFlame , please could you double check which jira issue this PR relates to.
> > 
> > 
> > I didn't saw on jira that 12818 was already used. I edited to 12822
> 
> Hi @MaximeFlame - I cannot view ticket OFBIZ-12822.
> 
> Have you created a Jira Issue corresponding to this PR? If so, please provide a link to the issue.
> 
> I would like to better understand the issue this PR is addressing as it may apply to languages other than French. Those sorts of discussion would be done in the comments of the Jira, and/or the mailing list if particularly complex.

I don't have the right to create Jira issue :/

**Comment by JacquesLeRoux** [comment]
Welcome @MaximeFlame  :)

**Comment by MaximeFlame** [comment]
> Welcome @MaximeFlame :)

Thanks You

**Comment by JacquesLeRoux** [comment]
Thank you @danwatford and @MaximeFlame

**Pull request merged**
