### PR TITLE
Improved: Use a version catalog

### PR DESCRIPTION
**Pull request by dtrunk90**
Using a version catalog makes things easier:
- You can update a single version for multiple artifacts (e.g. Tomcat)
- You have all the artifacts and their versions at a single place separated from other stuff

See also https://docs.gradle.org/current/userguide/platforms.html

### CODE REVIEW

**Comment by JacquesLeRoux** [comment]
Hi @dtrunk90, 

I remember having seen that before, but completly forgot about it. 
Could you please update the PR, or create anew. At 1st glance, the conflicts seem a bit hard to resolve

TIA

**Comment by dtrunk90** [comment]
Hi @JacquesLeRoux,

it took some hours but it's finally done.

**Comment by mbrohl** [comment]
@dtrunk90 Can you elaborate a bit more what advantages this approach brings?
At first glance it seems to make things more complicate?

**Comment by JacquesLeRoux** [comment]
Hi @dtrunk90, @mbrohl ,

I must say last time I just had a glance, notably on the Gradle Page. After reading a bit more there, with a glance as the resulting code here, I indeed wonder if we need that OOTB. 

@dtrunk90, I suggest to start a thread in the dev ML (dev@ofbiz.apache.org). That's what we do when we hesitate and want to make a community decision. Just few explaining words should be enough.

**Comment by JacquesLeRoux** [comment]
As a note, here is the Gradle page summary for the catalog feature:

> In summary, using a catalog is always a good engineering practice as it centralizes common definitions, allows sharing of dependency versions or plugin versions, but it is an "implementation detail" of the build: it will not be visible to consumers and unused elements of a catalog are just ignored.

Again, not sure we need that, we need to deal with it in depth.

**Pull request closed without merging**
