### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by Dmole**
Fixed: 404

### CODE REVIEW

**Comment by JacquesLeRoux** [comment]
Thanks for report @Dmole,

Actually it was a typo of mine, the link should have been https://nightlies.apache.org/ofbiz/trunk/readme/html5/DOCKER.html (or https://nightlies.apache.org/ofbiz/next/readme/html5/DOCKER.html it's not available in stable aka 18.12 branch)

**Comment by JacquesLeRoux** [comment]
Fixed with https://github.com/apache/ofbiz-framework/commit/7c16a97250df84cb831dc3fdbe8f194115aa0230

**Comment by mbrohl** [comment]
Should be backported to 24.09 I think.

**Comment by JacquesLeRoux** [comment]
Right, done

**Pull request closed without merging**
