### PR TITLE
Improved: Update Data Sets (OFBIZ-6976)

### PR DESCRIPTION
**Pull request by PierreSmits**
(OFBIZ-6976)(OFBIZ-11649)(OFBIZ-11650)(OFBIZ-11655)

added: party data into PartyComponentData from other components
removed: party data from Accounting component
removed: party data from Order component
removed: party data from Marketing plugin

### CODE REVIEW

**Comment by adityasharma7** [comment]
It seems there is some issue with this PR, it is showing 135 commits and 237 file changes. @PierreSmits Can you fix it?

**Comment by PierreSmits** [comment]
@adityasharma7 What is wrong with the PR? It doesn't merge?

**Comment by PierreSmits** [comment]
If the only issue regarding this PR is the number of commits and file changes...

**Comment by adityasharma7** [comment]
@PierreSmits Due to lots of other commits, reviewer won't be able to review your work

**Comment by PierreSmits** [comment]
Hi @adityasharma7,

I concur that it takes effort to review. 
As discussed with @JacquesLeRoux elsethread, best approach is it to
1. check out the branch, and also checkout the related PR from plugins
2. do a cleanAll loadAll within the checkout branch and see that everything loads.

**Comment by PierreSmits** [comment]
How is this check fail possible? 2 days ago everything was fine, and now it is stating that it failed. The only thing changed is added a few records in the demo set.

https://github.com/apache/ofbiz-framework/pull/117#issuecomment-639298833

**Comment by JacquesLeRoux** [comment]
Hi Pierre,

Maybe because SonarCloud Quality Gate mproved the checking rules? Better fix issues before merging I'd say.  I can do it if you prefer but not sure how this would merge with your code. We can also fix issues after merging, maybe easier, but we need to be reminded...

It seems (at 1st glance) you can neglect the code smells warning

**Comment by PierreSmits** [comment]
I do.

**Pull request closed without merging**
