### PR TITLE
Improvement of the Check xml tag (OFBIZ-12821)

### PR DESCRIPTION
**Pull request by MaximeFlame**
Added features :
- Pre-select / Pre-check
- -> Chose which should be pre-check
- Pre-unSelect / Pre-unCheck
- -> All checked and select whose should not be checked

EDIT : 

[OFBIZ-12821](https://issues.apache.org/jira/browse/OFBIZ-12821)

Thanks:
Néréide

### CODE REVIEW

**Comment by nmalin** [comment]
Hi @MaximeFlame,

Xml attributes checked-by-default and unchecked-by-default seems to add only code complexity without most value.

With the possibility to check form a pk list, you have natively this functionality through the prepare statement.

**Comment by MaximeFlame** [comment]
Code updated @nmalin

**Comment by JacquesLeRoux** [comment]
Hi @MaximeFlame,

Do your code changes answer to @nmalin's suggestion? BTW I don't clearly understand your suggestion Nicolas :)
Also there is a test issue...

**Comment by nmalin** [comment]
Hi @JacquesLeRoux, I shared with him on IRL,

I said we can have the same functionnality to precheck or uncheck easly with set the good id list on the context. So  adding two attributes to do that is redundant and finally add unnecessary code.

**Comment by JacquesLeRoux** [comment]
Nicolas, do you mean in the screen or java methods? Maybe we could document that. It's still not crystal clear to me, sorry

**Comment by MaximeFlame** [comment]
> Hi @MaximeFlame,
> 
> Do your code changes answer to @nmalin's suggestion? BTW I don't clearly understand your suggestion Nicolas :) Also there is a test issue...

Yes

**Comment by JacquesLeRoux** [comment]
Hi @nmalin, 

Thanks for the explanation, I got it looking at QuoteForms.xml where OTHER_QUOTE and PROPOSAL are preset.
I simply amended the doc in widget-form.xsd. I'll commit from my machine

**Pull request closed without merging**
